cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/templates  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/tags  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/static  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/single_measurements  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/recipes  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/recipe_ingredient_measurements  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/menu  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/krishnacook  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/ingredients  /mnt/sshfs/dev-cook/src ;
cp -v -R /home/web_dev/exclude/.virtualenvs/krishnacook/src/typeofingredient  /mnt/sshfs/dev-cook/src ;
touch /mnt/sshfs/dev-cook/src/krishnacook/wsgi.py ;
echo "****************************** END ************************" ;